server:
  port: 8083

spring:
  h2:
    console:
      enabled: true
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://Order-Service
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://Payment-Service
          predicates:
            - Path=/payment/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
  instance:
    hostname: localhost

